### ISSUE TITLE
拖拽功能无法使用

### ISSUE THREAD

**Issue by zgynhqf** [zgynhqf/AppShortcuts#5]
可以使用一个新的 Exe，以管理员启动，用于专门保存注册表。
而 AppShortcuts 本身不需要以管理员启动。

**Comment by zhuwansu** [comment]
参见 #9 
在保存时提示以管理员启动 AppShortcutsModel.exe 程序修改注册表。
如果拒绝则失败不会对 setting.xml 文件产生影响。
这样就既可以使用拖拽功能又可以保存了。

**Comment by zhuwansu** [comment]
AppShortcutsModel.exe 中设计了校验第一个参数（一个写死的 guid 简单票据），单独运行无任何效果（防止瞎点）。
